/*
 * API
 * API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.nk.klusterfuck.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * IntOrString
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-07-12T18:36:23.255+05:30")
public class IntOrString {
  @SerializedName("IntVal")
  private Integer intVal = null;

  @SerializedName("Kind")
  private Integer kind = null;

  @SerializedName("StrVal")
  private String strVal = null;

  public IntOrString intVal(Integer intVal) {
    this.intVal = intVal;
    return this;
  }

   /**
   * Get intVal
   * @return intVal
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getIntVal() {
    return intVal;
  }

  public void setIntVal(Integer intVal) {
    this.intVal = intVal;
  }

  public IntOrString kind(Integer kind) {
    this.kind = kind;
    return this;
  }

   /**
   * Get kind
   * @return kind
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getKind() {
    return kind;
  }

  public void setKind(Integer kind) {
    this.kind = kind;
  }

  public IntOrString strVal(String strVal) {
    this.strVal = strVal;
    return this;
  }

   /**
   * Get strVal
   * @return strVal
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStrVal() {
    return strVal;
  }

  public void setStrVal(String strVal) {
    this.strVal = strVal;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IntOrString intOrString = (IntOrString) o;
    return Objects.equals(this.intVal, intOrString.intVal) &&
        Objects.equals(this.kind, intOrString.kind) &&
        Objects.equals(this.strVal, intOrString.strVal);
  }

  @Override
  public int hashCode() {
    return Objects.hash(intVal, kind, strVal);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IntOrString {\n");
    
    sb.append("    intVal: ").append(toIndentedString(intVal)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    strVal: ").append(toIndentedString(strVal)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

