/**
 * API
 * API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface CreateFlowRequest {
    name?: string;

    template?: string;

    serviceType?: CreateFlowRequest.ServiceTypeEnum;

    ingress?: boolean;

    host?: string;

    path?: string;

}
export namespace CreateFlowRequest {
    export enum ServiceTypeEnum {
        ClusterIP = <any> 'ClusterIP',
        NodePort = <any> 'NodePort'
    }
}
