/**
 * API
 * API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface CreateFunctionRequest {
    name?: string;

    type?: CreateFunctionRequest.TypeEnum;

}
export namespace CreateFunctionRequest {
    export enum TypeEnum {
        Generic = <any> 'generic',
        Nodejs = <any> 'nodejs',
        StaticSite = <any> 'static_site'
    }
}
